# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure('2') do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = 'ubuntu/trusty64'
  (1..2).each do |x|
    config.vm.define "machine#{x}" do |machine|
      num = x
      machine.vm.hostname = "machine#{num}"
      machine.vm.network 'private_network', ip: "192.168.19.3#{num}"
      machine.vm.provision 'file', source: "html/machine#{num}.html", destination: '/tmp/index.html'
      machine.vm.provision 'shell', inline: <<-SHELL
        apt-get update
        apt-get install -y curl nginx
        sudo cp /tmp/index.html   /usr/share/nginx/html/index.html
      SHELL

    end
  end
end
